<?php

declare(strict_types=1);

/**
 * Copyright (c) 2024-2026 Andreas Möller
 *
 * For the full copyright and license information, please view
 * the LICENSE.md file that was distributed with this source code.
 *
 * @see https://github.com/ergebnis/keep-a-changelog
 */

namespace Ergebnis\KeepAChangelog\Test\Unit;

use Ergebnis\KeepAChangelog\Author;
use Ergebnis\KeepAChangelog\Changelog;
use Ergebnis\KeepAChangelog\Changes;
use Ergebnis\KeepAChangelog\DefaultBranch;
use Ergebnis\KeepAChangelog\Description;
use Ergebnis\KeepAChangelog\Entry;
use Ergebnis\KeepAChangelog\EntryList;
use Ergebnis\KeepAChangelog\InitialCommit;
use Ergebnis\KeepAChangelog\MarkdownBuffer;
use Ergebnis\KeepAChangelog\MarkdownRenderer;
use Ergebnis\KeepAChangelog\Name;
use Ergebnis\KeepAChangelog\Notes;
use Ergebnis\KeepAChangelog\Owner;
use Ergebnis\KeepAChangelog\PullRequest;
use Ergebnis\KeepAChangelog\Release;
use Ergebnis\KeepAChangelog\ReleaseList;
use Ergebnis\KeepAChangelog\Repository;
use Ergebnis\KeepAChangelog\Tag;
use Ergebnis\KeepAChangelog\Unreleased;
use PHPUnit\Framework;

/**
 * @covers \Ergebnis\KeepAChangelog\MarkdownRenderer
 *
 * @uses \Ergebnis\KeepAChangelog\Author
 * @uses \Ergebnis\KeepAChangelog\Changelog
 * @uses \Ergebnis\KeepAChangelog\Changes
 * @uses \Ergebnis\KeepAChangelog\DefaultBranch
 * @uses \Ergebnis\KeepAChangelog\Description
 * @uses \Ergebnis\KeepAChangelog\Entry
 * @uses \Ergebnis\KeepAChangelog\EntryList
 * @uses \Ergebnis\KeepAChangelog\InitialCommit
 * @uses \Ergebnis\KeepAChangelog\MarkdownBuffer
 * @uses \Ergebnis\KeepAChangelog\Name
 * @uses \Ergebnis\KeepAChangelog\Notes
 * @uses \Ergebnis\KeepAChangelog\Owner
 * @uses \Ergebnis\KeepAChangelog\PullRequest
 * @uses \Ergebnis\KeepAChangelog\Release
 * @uses \Ergebnis\KeepAChangelog\ReleaseList
 * @uses \Ergebnis\KeepAChangelog\Repository
 * @uses \Ergebnis\KeepAChangelog\Section
 * @uses \Ergebnis\KeepAChangelog\Tag
 * @uses \Ergebnis\KeepAChangelog\UnknownSection
 * @uses \Ergebnis\KeepAChangelog\Unreleased
 */
final class MarkdownRendererTest extends Framework\TestCase
{
    public function testRenderChangelogReturnsMarkdownWhenChangelogIsEmptyAndRepositoryDoesNotHaveInitialCommit(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                null,
            ),
            Unreleased::empty(),
            ReleaseList::empty(),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogIsEmptyAndRepositoryHasInitialCommit(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                InitialCommit::fromString('88cf670a0f2f73e01011a4f5e0feceb43411e0c9'),
            ),
            Unreleased::empty(),
            ReleaseList::empty(),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`88cf670a0f2f73e01011a4f5e0feceb43411e0c9...main`](https://github.com/ergebnis/keep-a-changelog/compare/88cf670a0f2f73e01011a4f5e0feceb43411e0c9...main).',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogHasUnreleasedChanges(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                InitialCommit::fromString('88cf670a0f2f73e01011a4f5e0feceb43411e0c9'),
            ),
            Unreleased::create(Changes::create(
                EntryList::create(
                    Entry::create(
                        Description::fromString('Added `Bar`'),
                        PullRequest::fromInt(15),
                        Author::fromString('localheinz'),
                        null,
                    ),
                    Entry::create(
                        Description::fromString('Added `Foo`'),
                        PullRequest::fromInt(12),
                        Author::fromString('localheinz'),
                        null,
                    ),
                ),
                EntryList::empty(),
                EntryList::empty(),
                EntryList::empty(),
                EntryList::create(
                    Entry::create(
                        Description::fromString('Fixed `Qux`'),
                        PullRequest::fromInt(14),
                        Author::fromString('localheinz'),
                        null,
                    ),
                    Entry::create(
                        Description::fromString('Fixed `Baz`'),
                        PullRequest::fromInt(13),
                        Author::fromString('localheinz'),
                        null,
                    ),
                ),
                EntryList::empty(),
            )),
            ReleaseList::empty(),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`88cf670a0f2f73e01011a4f5e0feceb43411e0c9...main`](https://github.com/ergebnis/keep-a-changelog/compare/88cf670a0f2f73e01011a4f5e0feceb43411e0c9...main).',
            '',
            '### Added',
            '',
            '- Added `Foo` ([#12](https://github.com/ergebnis/keep-a-changelog/pull/12)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Bar` ([#15](https://github.com/ergebnis/keep-a-changelog/pull/15)), by [@localheinz](https://github.com/localheinz)',
            '',
            '### Fixed',
            '',
            '- Fixed `Baz` ([#13](https://github.com/ergebnis/keep-a-changelog/pull/13)), by [@localheinz](https://github.com/localheinz)',
            '- Fixed `Qux` ([#14](https://github.com/ergebnis/keep-a-changelog/pull/14)), by [@localheinz](https://github.com/localheinz)',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogHasUnreleasedChangesWhereEntryHasNotes(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                InitialCommit::fromString('88cf670a0f2f73e01011a4f5e0feceb43411e0c9'),
            ),
            Unreleased::create(Changes::create(
                EntryList::create(
                    Entry::create(
                        Description::fromString('Added `Foo`'),
                        PullRequest::fromInt(12),
                        Author::fromString('localheinz'),
                        Notes::fromString("This is a longer note\nthat spans multiple lines."),
                    ),
                    Entry::create(
                        Description::fromString('Added `Bar`'),
                        PullRequest::fromInt(15),
                        Author::fromString('localheinz'),
                        null,
                    ),
                ),
                EntryList::empty(),
                EntryList::empty(),
                EntryList::empty(),
                EntryList::empty(),
                EntryList::empty(),
            )),
            ReleaseList::empty(),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`88cf670a0f2f73e01011a4f5e0feceb43411e0c9...main`](https://github.com/ergebnis/keep-a-changelog/compare/88cf670a0f2f73e01011a4f5e0feceb43411e0c9...main).',
            '',
            '### Added',
            '',
            '- Added `Foo` ([#12](https://github.com/ergebnis/keep-a-changelog/pull/12)), by [@localheinz](https://github.com/localheinz)',
            '',
            '  This is a longer note',
            '  that spans multiple lines.',
            '',
            '- Added `Bar` ([#15](https://github.com/ergebnis/keep-a-changelog/pull/15)), by [@localheinz](https://github.com/localheinz)',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogHasReleaseWithoutChanges(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                InitialCommit::fromString('88cf670a0f2f73e01011a4f5e0feceb43411e0c9'),
            ),
            Unreleased::create(Changes::empty()),
            ReleaseList::create(Release::create(
                Tag::fromString('1.0.0'),
                Changes::empty(),
            )),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`1.0.0...main`](https://github.com/ergebnis/keep-a-changelog/compare/1.0.0...main).',
            '',
            '## [`1.0.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.0.0)',
            '',
            'For a full diff see [`88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0`](https://github.com/ergebnis/keep-a-changelog/compare/88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0).',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogHasReleaseWithChanges(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                InitialCommit::fromString('88cf670a0f2f73e01011a4f5e0feceb43411e0c9'),
            ),
            Unreleased::empty(),
            ReleaseList::create(
                Release::create(
                    Tag::fromString('1.0.0'),
                    Changes::create(
                        EntryList::create(
                            Entry::create(
                                Description::fromString('Added `Bar`'),
                                PullRequest::fromInt(15),
                                Author::fromString('localheinz'),
                                null,
                            ),
                            Entry::create(
                                Description::fromString('Added `Foo`'),
                                PullRequest::fromInt(12),
                                Author::fromString('localheinz'),
                                null,
                            ),
                        ),
                        EntryList::empty(),
                        EntryList::empty(),
                        EntryList::empty(),
                        EntryList::create(
                            Entry::create(
                                Description::fromString('Fixed `Qux`'),
                                PullRequest::fromInt(14),
                                Author::fromString('localheinz'),
                                null,
                            ),
                            Entry::create(
                                Description::fromString('Fixed `Baz`'),
                                PullRequest::fromInt(13),
                                Author::fromString('localheinz'),
                                null,
                            ),
                        ),
                        EntryList::empty(),
                    ),
                ),
                Release::create(
                    Tag::fromString('1.1.0'),
                    Changes::create(
                        EntryList::create(
                            Entry::create(
                                Description::fromString('Added `Baz`'),
                                PullRequest::fromInt(20),
                                Author::fromString('localheinz'),
                                Notes::fromString("This required a migration.\nSee UPGRADING.md for details."),
                            ),
                            Entry::create(
                                Description::fromString('Added `Qux`'),
                                PullRequest::fromInt(10),
                                Author::fromString('localheinz'),
                                null,
                            ),
                        ),
                        EntryList::empty(),
                        EntryList::empty(),
                        EntryList::empty(),
                        EntryList::empty(),
                        EntryList::empty(),
                    ),
                ),
            ),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`1.1.0...main`](https://github.com/ergebnis/keep-a-changelog/compare/1.1.0...main).',
            '',
            '## [`1.1.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.1.0)',
            '',
            'For a full diff see [`1.0.0...1.1.0`](https://github.com/ergebnis/keep-a-changelog/compare/1.0.0...1.1.0).',
            '',
            '### Added',
            '',
            '- Added `Qux` ([#10](https://github.com/ergebnis/keep-a-changelog/pull/10)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Baz` ([#20](https://github.com/ergebnis/keep-a-changelog/pull/20)), by [@localheinz](https://github.com/localheinz)',
            '',
            '  This required a migration.',
            '  See UPGRADING.md for details.',
            '',
            '## [`1.0.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.0.0)',
            '',
            'For a full diff see [`88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0`](https://github.com/ergebnis/keep-a-changelog/compare/88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0).',
            '',
            '### Added',
            '',
            '- Added `Foo` ([#12](https://github.com/ergebnis/keep-a-changelog/pull/12)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Bar` ([#15](https://github.com/ergebnis/keep-a-changelog/pull/15)), by [@localheinz](https://github.com/localheinz)',
            '',
            '### Fixed',
            '',
            '- Fixed `Baz` ([#13](https://github.com/ergebnis/keep-a-changelog/pull/13)), by [@localheinz](https://github.com/localheinz)',
            '- Fixed `Qux` ([#14](https://github.com/ergebnis/keep-a-changelog/pull/14)), by [@localheinz](https://github.com/localheinz)',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogHasReleaseWithChangesWhereEntryHasNotes(): void
    {
        $repository = Repository::create(
            Owner::fromString('ergebnis'),
            Name::fromString('keep-a-changelog'),
            DefaultBranch::fromString('main'),
            InitialCommit::fromString('88cf670a0f2f73e01011a4f5e0feceb43411e0c9'),
        );

        $unreleased = Unreleased::empty();

        $releases = ReleaseList::create(
            Release::create(
                Tag::fromString('1.0.0'),
                Changes::create(
                    EntryList::create(
                        Entry::create(
                            Description::fromString('Added `Foo`'),
                            PullRequest::fromInt(3),
                            Author::fromString('localheinz'),
                            null,
                        ),
                        Entry::create(
                            Description::fromString('Added `Bar`'),
                            PullRequest::fromInt(1),
                            Author::fromString('localheinz'),
                            null,
                        ),
                    ),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                ),
            ),
            Release::create(
                Tag::fromString('1.1.0'),
                Changes::create(
                    EntryList::create(
                        Entry::create(
                            Description::fromString('Added `Baz`'),
                            PullRequest::fromInt(20),
                            Author::fromString('localheinz'),
                            Notes::fromString("This required a migration.\nSee UPGRADING.md for details."),
                        ),
                        Entry::create(
                            Description::fromString('Added `Qux`'),
                            PullRequest::fromInt(10),
                            Author::fromString('localheinz'),
                            null,
                        ),
                    ),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                ),
            ),
        );

        $changelog = Changelog::create(
            $repository,
            $unreleased,
            $releases,
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`1.1.0...main`](https://github.com/ergebnis/keep-a-changelog/compare/1.1.0...main).',
            '',
            '## [`1.1.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.1.0)',
            '',
            'For a full diff see [`1.0.0...1.1.0`](https://github.com/ergebnis/keep-a-changelog/compare/1.0.0...1.1.0).',
            '',
            '### Added',
            '',
            '- Added `Qux` ([#10](https://github.com/ergebnis/keep-a-changelog/pull/10)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Baz` ([#20](https://github.com/ergebnis/keep-a-changelog/pull/20)), by [@localheinz](https://github.com/localheinz)',
            '',
            '  This required a migration.',
            '  See UPGRADING.md for details.',
            '',
            '## [`1.0.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.0.0)',
            '',
            'For a full diff see [`88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0`](https://github.com/ergebnis/keep-a-changelog/compare/88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0).',
            '',
            '### Added',
            '',
            '- Added `Bar` ([#1](https://github.com/ergebnis/keep-a-changelog/pull/1)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Foo` ([#3](https://github.com/ergebnis/keep-a-changelog/pull/3)), by [@localheinz](https://github.com/localheinz)',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogHasUnreleasedAndReleasedEntries(): void
    {
        $repository = Repository::create(
            Owner::fromString('ergebnis'),
            Name::fromString('keep-a-changelog'),
            DefaultBranch::fromString('main'),
            InitialCommit::fromString('88cf670a0f2f73e01011a4f5e0feceb43411e0c9'),
        );

        $unreleased = Unreleased::create(Changes::create(
            EntryList::create(
                Entry::create(
                    Description::fromString('Added `Quux`'),
                    PullRequest::fromInt(30),
                    Author::fromString('localheinz'),
                    null,
                ),
                Entry::create(
                    Description::fromString('Added `Corge`'),
                    PullRequest::fromInt(25),
                    Author::fromString('localheinz'),
                    null,
                ),
            ),
            EntryList::empty(),
            EntryList::empty(),
            EntryList::empty(),
            EntryList::empty(),
            EntryList::empty(),
        ));

        $releases = ReleaseList::create(
            Release::create(
                Tag::fromString('1.0.0'),
                Changes::create(
                    EntryList::create(
                        Entry::create(
                            Description::fromString('Added `Foo`'),
                            PullRequest::fromInt(3),
                            Author::fromString('localheinz'),
                            null,
                        ),
                        Entry::create(
                            Description::fromString('Added `Bar`'),
                            PullRequest::fromInt(1),
                            Author::fromString('localheinz'),
                            null,
                        ),
                    ),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                ),
            ),
            Release::create(
                Tag::fromString('1.1.0'),
                Changes::create(
                    EntryList::create(
                        Entry::create(
                            Description::fromString('Added `Baz`'),
                            PullRequest::fromInt(20),
                            Author::fromString('localheinz'),
                            null,
                        ),
                        Entry::create(
                            Description::fromString('Added `Qux`'),
                            PullRequest::fromInt(10),
                            Author::fromString('localheinz'),
                            null,
                        ),
                    ),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                ),
            ),
        );

        $changelog = Changelog::create(
            $repository,
            $unreleased,
            $releases,
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`1.1.0...main`](https://github.com/ergebnis/keep-a-changelog/compare/1.1.0...main).',
            '',
            '### Added',
            '',
            '- Added `Corge` ([#25](https://github.com/ergebnis/keep-a-changelog/pull/25)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Quux` ([#30](https://github.com/ergebnis/keep-a-changelog/pull/30)), by [@localheinz](https://github.com/localheinz)',
            '',
            '## [`1.1.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.1.0)',
            '',
            'For a full diff see [`1.0.0...1.1.0`](https://github.com/ergebnis/keep-a-changelog/compare/1.0.0...1.1.0).',
            '',
            '### Added',
            '',
            '- Added `Qux` ([#10](https://github.com/ergebnis/keep-a-changelog/pull/10)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Baz` ([#20](https://github.com/ergebnis/keep-a-changelog/pull/20)), by [@localheinz](https://github.com/localheinz)',
            '',
            '## [`1.0.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.0.0)',
            '',
            'For a full diff see [`88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0`](https://github.com/ergebnis/keep-a-changelog/compare/88cf670a0f2f73e01011a4f5e0feceb43411e0c9...1.0.0).',
            '',
            '### Added',
            '',
            '- Added `Bar` ([#1](https://github.com/ergebnis/keep-a-changelog/pull/1)), by [@localheinz](https://github.com/localheinz)',
            '- Added `Foo` ([#3](https://github.com/ergebnis/keep-a-changelog/pull/3)), by [@localheinz](https://github.com/localheinz)',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogReturnsMarkdownWhenChangelogHasReleaseWithoutInitialCommit(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                null,
            ),
            Unreleased::empty(),
            ReleaseList::create(Release::create(
                Tag::fromString('1.0.0'),
                Changes::create(
                    EntryList::create(Entry::create(
                        Description::fromString('Added `Foo`'),
                        PullRequest::fromInt(1),
                        Author::fromString('localheinz'),
                        null,
                    )),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                    EntryList::empty(),
                ),
            )),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '## Unreleased',
            '',
            'For a full diff see [`1.0.0...main`](https://github.com/ergebnis/keep-a-changelog/compare/1.0.0...main).',
            '',
            '## [`1.0.0`](https://github.com/ergebnis/keep-a-changelog/releases/tag/1.0.0)',
            '',
            '### Added',
            '',
            '- Added `Foo` ([#1](https://github.com/ergebnis/keep-a-changelog/pull/1)), by [@localheinz](https://github.com/localheinz)',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    public function testRenderChangelogClearsBufferBetweenCalls(): void
    {
        $changelog = Changelog::create(
            Repository::create(
                Owner::fromString('ergebnis'),
                Name::fromString('keep-a-changelog'),
                DefaultBranch::fromString('main'),
                null,
            ),
            Unreleased::empty(),
            ReleaseList::empty(),
        );

        $markdownRenderer = new MarkdownRenderer();

        $expected = self::buffered(
            '# Changelog',
            '',
            'All notable changes to this project will be documented in this file.',
            '',
            'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).',
            '',
            '<!-- generated by ergebnis/keep-a-changelog -->',
        );

        $markdownRenderer->renderChangelog($changelog);

        self::assertSame($expected, $markdownRenderer->renderChangelog($changelog));
    }

    private static function buffered(string ...$lines): string
    {
        $markdownBuffer = new MarkdownBuffer();

        $markdownBuffer->append(...$lines);

        return $markdownBuffer->flush();
    }
}
